[package]
name = "model2vec_infer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
candle-core = "0.7.2"
candle-nn = "0.7.2"
hf-hub = "0.3.2"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokenizers = { version = "0.20.1", features = ["http"] }
